import type { Metadata } from "next";
import "../globals.css";
import { ConfigProvider } from "antd";
import { colors } from "@/constants/colors";

export const metadata: Metadata = {
    title: "Marathon App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ConfigProvider
            theme={{
                token: {
                    colorPrimary: colors.primary,
                },
            }}
        >
            <html lang="en">
                <body>{children}</body>
            </html>
        </ConfigProvider>
    );
}
